### PR TITLE
Tweak logged event JSON to be inconsistent in a different way

### PR DESCRIPTION
**Pull request by NickGrantONS**
# Motivation and Context
We were logging our event JSON inconsistently. We want to log it in a different way, but still inconsistently... but it's hopefully what's been agreed with Rob S and DAP, so it might be OK.

# What has changed
Did the changes requested by Rob S.

# How to test?
Don't bother - there are ITs. DAP will ingest the data eventually and tell is if it's OK for them.

# Links
Trello: https://trello.com/c/R3awWPFz

### CODE REVIEW

**Comment by NickGrantONS** [comment]
[change stored event data structure (5)](https://trello.com/c/R3awWPFz/1331-change-stored-event-data-structure-5)

**Comment by davidmort** [comment]
@NickGrantONS not sure the PR description here is particularly helpful......what are the other inconsistencies?

**Review by AdamHawtin — APPROVED** [review]
LGTM 👍

**Comment by NickGrantONS** [comment]
> @NickGrantONS not sure the PR description here is particularly helpful......what are the other inconsistencies?

Well, everywhere is now inconsistent with fieldcaseupdated... and we haven't done our own review of the code to check for inconsistencies, but that means approx 14 places

**Pull request merged**
